apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  storageClassName: mongodb-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

